### ISSUE TITLE
How to access private registry?

### ISSUE THREAD

**Issue by ArtemAvramenko** [Microsoft/vs-setup-samples#1]
I created the installer that changes some settings in Visual Studio 2015 via registry (HKCU\Software\Microsoft\VisualStudio\14.0)

The samples do not show how to change registry settings in Visual Studio "15"

https://blogs.msdn.microsoft.com/heaths/2016/09/15/changes-to-visual-studio-15-setup/
> Each instance also has its own private registry so they can be configured independently.

How to access this registry from my code?

**Comment by heaths** [comment]
Extensions running from within VS will be redirected automatically, but whether running inside or outside VS, this is beyond the scope of this sample. The VSIP program will have more information later. For now, I encourage you to visit https://vspartner.com/.

I will refer your question to the Visual Studio SDK team for further comment, but otherwise closing the issue since it's unrelated to the sample code to find information about existing instances.

**Comment by MikhailTymchukDX** [comment]
Hi,

I have a problem with [Microsoft.VisualStudio.Settings.15.0](https://www.nuget.org/packages/Microsoft.VisualStudio.Settings.15.0/15.0.25824-RC) package.

When I try to load settings with [`ExternalSettingsManager.CreateForApplication(devenvPath);`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.settings.externalsettingsmanager.aspx) call, an exception is thrown:

![image](https://cloud.githubusercontent.com/assets/17080984/21380370/de1c9956-c765-11e6-8009-b73551a51eb1.png)

How to fix it?

**Comment by heaths** [comment]
@MikhailTymchukDX that isn't directly related to this bug. Please visit https://gitter.im/Microsoft/extendvs for general help with extending VS.
