### ISSUE TITLE
Examples need to be updated

### ISSUE THREAD

**Issue by suprak** [Microsoft/vs-setup-samples#7]
The CS example does not work for me.
Also the readme shows a completely different way of accessing the functionality,

`[DllImport("Microsoft.VisualStudio.Setup.Configuration.Native.dll", ExactSpelling = true, PreserveSig = true)]
        private static extern int GetSetupConfiguration([MarshalAs(UnmanagedType.Interface), Out] out ISetupConfiguration configuration, IntPtr reserved);`

vs

`new SetupConfiguration();`

The latter one works, the former fails since .Native.dll cannot be found.

https://blogs.msdn.microsoft.com/heaths/2016/09/15/changes-to-visual-studio-15-setup/

**Comment by heaths** [comment]
I no longer call the P/Invoke. It was for testing. But what doesn't work exactly? All the code is tested before I push.

**Comment by suprak** [comment]
So it went like this,

 - I was researching the Setup Configuration API
 - I came upon a lot of examples that used and referenced pinvoke including VS Community discussions (from Preview time frame)
 - I could not get pinvoke to work
 - I stumbled upon this repo and browsed the source and it **appeared** to me that you also relied on pinvoke, hence my comment

If it's test code, fine, but it shouldn't appear in the main "example" file. Since it is misleading.

**Comment by heaths** [comment]
I'm the one who wrote the COM server, the blog posts about the API, this sample, and the various tools in the Microsoft org on GitHub. Consider these authoritative. ;)

I already removed the code from the samples previously that used the P/Invoke. I had other aspirations from it that didn't pan out and am not going to remove the entry point because 1) it would be a breaking change, and 2) we still use it internally for some integration tests. I can remove the P/Invoke declaration, but that really shouldn't matter since nothing should be calling it.

Just create a new `SetupConfiguration` and catch the specific `COMException` with `REGDB_E_CLASSNOTREG` meaning "no instances". Since you're using managed, see https://github.com/Microosft/vssetup.powershell for the cmdlets I wrote that use this API for discovery and deeper analysis than https://github.com/Microsoft/vswhere.

**Comment by suprak** [comment]
👍

**Comment by heaths** [comment]
Reopening as a reminder to delete the P/Invoke declarations.

**Comment by heaths** [comment]
Resolved in commit 52d379e906eb3f39c70b6dc13755e2041c32988a.
