### ISSUE TITLE
Remove dependency on Nuget 

### ISSUE THREAD

**Issue by dougbinks** [Microsoft/vs-setup-samples#8]
This project has a dependency on Nuget which should be possible to be removed by adding the required code to this repository or creating it's own repo and adding that as a submodule. Note I am speaking here as a C & C++ developer, I am not sure what the consensus in other communities is.

As it stands, the dependencies are not clear, and turning this into a working lightweight solution is much harder.  Take a look at [the first response here by David Moore](https://developercommunity.visualstudio.com/content/problem/2813/cant-find-registry-entries-for-visual-studio-2017.html) for the sort of thing developers are looking to use instead of the code here.

I would expect all required dll's for querying the install to be installed along with the install of VS2017. I also would expect any code needed to query this would be extremely simple - all complexity of actual implementation should be handled in the library code installed alongside VS. Sadly it looks like this is now too late, but at the very least an example with minimal dependencies should be produced.

**Comment by refack** [comment]
I have whittled down this example to [something that uses only built-in windows tools](https://github.com/node4good/msvs-com-helper).
At worse you can copy the COM interface (which is what the `nuget` package provides).

Also check out @heaths 's https://github.com/Microsoft/vswhere

**Comment by refack** [comment]
Also be sure to upvote https://developercommunity.visualstudio.com/content/problem/35325/missing-vs150comntools.html

**Comment by dougbinks** [comment]
Thanks @refack that's helpful. In the end I am able to use the key in:

SOFTWARE\Microsoft\VisualStudio\SxS\VS7\15.0\

as this has the root folder which I can then find VC\Auxiliary\Build\vcvarsall.bat from which is what I need. However a simple official example would still be useful.

**Comment by refack** [comment]
@dougbinks MS don't garantee that key will be there (even within the VS2017 lifecycle). Follow the conversation at https://codereview.chromium.org/2754263002/
especially the caveat mentioned in http://code.qt.io/cgit/qt-labs/qbs.git/commit/?id=72463bbd87044148fcafcdc2c1189aa7a5593cf9

**Comment by dougbinks** [comment]
I'm going to stick with the registry setting until such a time as they disappear it. Hopefully by then we'll have a decent environment variable, code sample, or registry key to use.

**Comment by refack** [comment]
Make sure to look for the Buildtools SKU, using it is the strongest indicator to MS that that's the kind of product we want

**From the QT installer**
```c
// Detect Visual C++ Build Tools
   QSettings vcbtRegistry(
               QStringLiteral("HKEY_LOCAL_MACHINE\\SOFTWARE") + wow6432Key()
               + QStringLiteral("\\Microsoft\\VisualCppBuildTools"),
               QSettings::NativeFormat);
   const QStringList &vcbtRegistryChildGroups = vcbtRegistry.childGroups();
   for (const QString &childGroup : vcbtRegistryChildGroups) {
       vcbtRegistry.beginGroup(childGroup);
       bool ok;
       int installed = vcbtRegistry.value(QStringLiteral("Installed")).toInt(&ok);
       if (ok && installed) {
           MSVCRegistryEntry entry;
           entry.version = childGroup;
           const QSettings vsRegistry(
                       QStringLiteral("HKEY_LOCAL_MACHINE\\SOFTWARE") + wow6432Key()
                       + QStringLiteral("\\Microsoft\\VisualStudio\\") + childGroup
                       + QStringLiteral("\\Setup\\VC"),
                       QSettings::NativeFormat);
           entry.installDir = vsRegistry.value(QStringLiteral("ProductDir")).toString();
           result.append(entry);
       }
       vcbtRegistry.endGroup();
   }
```

**Comment by refack** [comment]
2017 Build tools https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15#
2015 Build tools http://landinghub.visualstudio.com/visual-cpp-build-tools
HOWTO command line install https://blogs.msdn.microsoft.com/vcblog/2016/11/16/introducing-the-visual-studio-build-tools/

**Comment by heaths** [comment]
With multi-instancing and **much** more granular feature selections, an environment variable does not provide you with any guarantees of what is installed which is why tools like _vswhere_ allow you to specify which features you actually require. We will be including _vswhere_ in the install in a well-known and relatively fixed location (using a common environment variable defined by Windows would be required to find the root, but that would be all).

Indeed, the registry key is not supported and probably will be removed at some point (same problems as with an environment variable) at which point _vswhere_ can be used.

As for the original issue, package managers such as nuget (which work for VC++, C#, VB.NET projects and more), NPM, bower, pip, and more are common these days. The VC++ team has also been building vcpkg as a more capable alternative to nuget for including heads, libs, and compiler settings into native projects - even for cross-platform code. We will not be duplicating the headers and will use the nuget package as a way to componentize and better support development of this and other modules. That's what package managers are for: componentization of discrete portions of software. Package managers such as NPM even support version comparisons of semantic versions to say you will support any major or minor releases or to fix on a particular version (something nuget lacks, unfortunately).

The DLLs to query VS are included in the install. This is sample code how to call into it. You can use _vswhere_ - either by pulling it down as a package or checking it in - or wait until we include it in the install but you'll still need to call into it.

**Comment by refack** [comment]
> With multi-instancing and much more granular feature selections, an environment variable does not provide you with any guarantees of what is installed which is why tools like `vswhere` allow you to specify which features you actually require. We will be including `vswhere` in the install in a well-known and relatively fixed location (using a common environment variable defined by Windows would be required to find the root, but that would be all).

Thank you from a huge community! (although adding an option in the vs_installer to select "default" instance would be just as great)

**Comment by dougbinks** [comment]
Including vswhere as a DLL in a well-kown fixed location using a common environment variable defined by windows would be a great step forwards.

The programming community I am from (C and C++ games programmers) does not look look kindly on package managers, hence the original request.

**Comment by dougbinks** [comment]
According to this blog: https://blogs.msdn.microsoft.com/vcblog/2017/03/06/finding-the-visual-c-compiler-tools-in-visual-studio-2017/

a simpler solution exists without dependency on nuget here:

https://github.com/mluparu/vs-setup-samples/tree/master/Setup.Configuration.VC.NoDeps

**Comment by heaths** [comment]
@dougbinks if you want to duplicate and maintain duplicate code feel free. Package managers exist to avoid such a coding practice. It's not like using nuget means you always get the latest. Nuget, unlike NPM, does not support a syntax to grab a newer version than what you specify in a _packages.config_ file. Your call, but the sample will continue to use the recommendation of a nuget package to avoid duplication.

Starting with 15.2 Preview 2 _vswhere_ is also now in the box: https://blogs.msdn.microsoft.com/heaths/2017/04/21/vswhere-is-now-installed-with-visual-studio-2017/
